### PR TITLE
Fix typos in the HighScore exercise introduction

### PR DESCRIPTION
**Pull request by sevenseacat**
`Example.example_value/0` definitely shouldn't return the value `2`!

Screen Shot 2021-09-04 at 11 32 38 am

### CODE REVIEW

**Review by jiegillet — APPROVED** [review]
I couldn't agree more. Thank you :)

**Comment by angelikatyborska** [comment]
The same content appears in the introduction files for those concepts. Can you fix that too?

https://github.com/exercism/elixir/blob/main/concepts/module-attributes-as-constants/introduction.md
https://github.com/exercism/elixir/blob/main/concepts/maps/introduction.md

Almost all concept exercise introductions are copies of concept introductions. We're waiting on https://github.com/exercism/elixir/issues/686 to be possible to just use a template instead.

**Comment by sevenseacat** [comment]
will do!

**Comment by angelikatyborska** [comment]
Thank you 💜 

@jiegillet you responded here first, do the merging honors 🎉

**Pull request merged**
