### PR TITLE
Sync sgf-parsing

### PR DESCRIPTION
**Pull request by angelikatyborska**
Problem specifications PR: https://github.com/exercism/problem-specifications/pull/1889/files

Missing updated solution

### CODE REVIEW

**Comment by angelikatyborska** [comment]
@jiegillet Would you want to provide an updated example solution here? This exercise is your baby, and it's way above my head

**Comment by neenjaw** [comment]
I can take a look at this as well since I have a solution for this exercise. I'll try look tonight after kids get to bed

**Comment by jiegillet** [comment]
Sorry for the super slow responses these days, I'm in a low point of motivation. I'll bounce back :)

I fixed my solution, but I've also had to make fixes to the test cases in [a7cd9a9](https://github.com/exercism/elixir/pull/1299/commits/a7cd9a919b269c6000aaef13ad94a23b2586bb78) to follow the problem-specs, please look these over, all this escaping messes with my mind.

**Review by jiegillet — APPROVED** [review]

**Comment by angelikatyborska** [comment]
Sorry about the broken tests 😇

**Pull request merged**
