### PR TITLE
Use the type testing functions

### PR DESCRIPTION
**Pull request by mikegehard**
This is more explicit about what the expectation is.

### CODE REVIEW

**Comment by angelikatyborska** [comment]
Thank you for the suggestion, but I disagree with the change. I think the change makes the test output in case of a failure less understandable, and it also removes the extra check of what the actual value is.

Before your changes, a failed test shows the expected number and the returned number line by line, with a highlighted `.0`, making the difference very clear. You can see immediately that your implementation returned an integer and not a float.

Screenshot 2024-08-11 at 12 27 58

After your changes, a failed test's highlighted part says "expected true, got false", which is a bit unclear for a function that returns a number, not a boolean. You have to read the whole test to notice that it calls `is_float`. Additionally, this failure doesn't tell you at all what is the type of the value that you returned. It only tells you that you didn't return a float.

Screenshot 2024-08-11 at 12 27 47


For this reason, I have to reject this PR.

**Comment by mikegehard** [comment]
Thanks for the feedback. Is there any room for a discussion on the pros/cons of each approach or is this decision final?

**Comment by angelikatyborska** [comment]
I consider this to be a very minor issue and would rather not spend more of my time on it, but if you have more thoughts on the topic, you can share them.

**Comment by mikegehard** [comment]
Gotcha. I don't want to take up more of your time.

**Pull request closed without merging**
