### PR TITLE
Rename roman-numerals function to 'numeral' for better reading

### PR DESCRIPTION
**Pull request by cetinajero**
This should only be merged after #477

### CODE REVIEW

**Comment by devonestes** [comment]
Same thing here - just needs to be updated to the new exercise structure.

**Comment by cetinajero** [comment]
This PR is also ready for review @devonestes, if anything else please let me know.

**Comment by devonestes** [comment]
@centinajero just a merge conflict here now and then I can merge this one too.

**Comment by cetinajero** [comment]
Done @devonestes 👍

**Pull request merged**
