### PR TITLE
Add fetch_configlet.sh

### PR DESCRIPTION
**Pull request by angelikatyborska**
Copied from https://github.com/exercism/github-actions/blob/main/configlet-ci/fetch-configlet, added a case statement to allow choosing the platform.

To be used by maintainers manually, when they want to lint the track before submitting a PR, for example.

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
@angelikatyborska While using the GHA script works with this modification, we actually have a script version for tracks: https://github.com/exercism/configlet/blob/main/scripts/fetch-configlet

That script has the platform option built-in as well as some other features.

**Comment by angelikatyborska** [comment]
Perfect! I guess I didn't look hard enough for it :D

**Review by ErikSchierboom — APPROVED** [review]
Great!

**Comment by ErikSchierboom** [comment]
> Perfect! I guess I didn't look hard enough for it :D

Well, you'd have to know, so it is more on our side :)

**Pull request merged**
