### PR TITLE
add version 0.0.0 to each exercise

### PR DESCRIPTION
**Pull request by neenjaw**
- creates `exercises/{slug}/.meta/version` file with the inital version set to `0.0.0`

### CODE REVIEW

**Comment by Cohen-Carlisle** [comment]
Can you explain what these changes do? Is the version related to the canonical data from problem specifications?

**Comment by neenjaw** [comment]
Forgot to link #506, yes, it is in regard to the problem specification and the track maintenance tool at https://tracks.exercism.io

**Comment by devonestes** [comment]
LGTM :+1:

**Comment by neenjaw** [comment]
@cohen-carlisle, in order to make use of the track maintenance tool, we need to add in what version our tests are built from. 

Since this repo doesn't currently track it, and adding them all with their current actual version is a lot of work. My thought is that by adding this with version `0.0.0` should at least make it so that the tool works for us so we can then start to pick away at the more time consuming labeling work.

**Comment by neenjaw** [comment]
Ok, I've been looking over some of the other tracks, it is not uncommon for tracks to list exercises at version `0.0.0`, I think we should just merge this to get the tool running...

**Comment by SleeplessByte** [comment]
Once [this](https://github.com/exercism/tracks-maintenance-dashboard/commit/ce69f0c886e9c4f1f11d102662b57b13fe012740/checks?check_suite_id=258741262) is green, it will be live [here](https://tracks.exercism.io/elixir/master/versions).

**Pull request merged**
