### PR TITLE
Deprecate IO.read warning in Newsletter exercise

### PR DESCRIPTION
**Pull request by lorisp1**
Hi, test `close_log closes the file` contained in Newsletter exercise is reporting the following warning if run with Elixir 1.17.1:
```
* test close_log closes the file [L#86]warning: IO.read(device, :all) is deprecated, use IO.read(device, :eof) instead
  (elixir 1.17.1) lib/io.ex:157: IO.read/2
  test/newsletter_test.exs:89: NewsletterTest."test close_log closes the file"/1
  (ex_unit 1.17.1) lib/ex_unit/runner.ex:485: ExUnit.Runner.exec_test/2
  (stdlib 5.2.3) timer.erl:270: :timer.tc/2
  (ex_unit 1.17.1) lib/ex_unit/runner.ex:407: anonymous fn/6 in ExUnit.Runner.spawn_test_monitor/4
```
This PR changes `IO.read` function call as suggested by the warning.

### CODE REVIEW

**Comment by angelikatyborska** [comment]
Thanks!

**Comment by angelikatyborska** [comment]
Ah, right, we can't just merge this because tests must work in many Elixir versions... @jiegillet thoughts?

**Comment by jiegillet** [comment]
The `:eof` value seems to [have been inserted in 1.13](https://hexdocs.pm/elixir/1.13.4/changelog.html), so 1.12 is failing.

[Version 1.12 doesn't get security patches anymore](https://hexdocs.pm/elixir/compatibility-and-deprecations.html), I can only assume that the timing for hard deprecation is linked to that. In that light, I think we could drop support for 1.12, if it's not officially safe, it makes sense for Exercism not to encourage people using it.

**Comment by jiegillet** [comment]
@lorisp1 could you rebase this on main? (or merge main)

**Review by angelikatyborska — APPROVED** [review]

**Comment by angelikatyborska** [comment]
Thanks again!

**Pull request merged**
