### PR TITLE
Make newsletter exercise tests run async

### PR DESCRIPTION
**Pull request by halfdan**
I just went through this exercise as part of the Exhort. It seemed trivial to make this exercise run tests asynchronous by generating random temp files using some core utils.

### CODE REVIEW

**Comment by zorn** [comment]
My understanding is that marking a test module as `async` only enables concurrent testing against other modules. The individual tests of a single module always run sequentially. 🤷‍♂️ 

https://hexdocs.pm/ex_unit/main/ExUnit.Case.html

**Comment by angelikatyborska** [comment]
@zorn You're absolutely right. This existing code with the comment in the tests should never have been added:

```elixir
  # run test synchronously to be able to use the same file path for all tests without write conflicts
  use ExUnit.Case, async: false
```

Our bad 🙈. But that also means this PR isn't really needed. We just need to remove the snippet I posted above to avoid future confusion.

**Comment by halfdan** [comment]
Hah, well TIL.

Happy to update/change the PR to remove that little snippet. Thanks to both of you.

**Comment by angelikatyborska** [comment]
> Happy to update/change the PR to remove that little snippet

That would be much appreciated!

**Comment by jiegillet** [comment]
@halfdan are you still interested in finishing this PR?
We can add the hacktoberfest label to it if you're interested.

**Comment by halfdan** [comment]
Yep, still happy to finish this. The tag would be a nice perk.

**Review by jiegillet — APPROVED** [review]
Sorry I took over in the end. Thanks for bringing this up though!

**Comment by halfdan** [comment]
@jiegillet Perfectly fine - sorry for dropping the ball here.

**Pull request merged**
