### PR TITLE
Mapping side exercises to core exercises.  First attempt.

### PR DESCRIPTION
**Pull request by neenjaw**
#474 See issue describing the motivation for this pull request.

Changes made: 
- ~~added a txt file to show which core exercises unlock which side exercises~~
- All side exercises are now mapped to a core exercise.
- The grep exercise difficulty increased to equal the bob problem

### CODE REVIEW

**Comment by Cohen-Carlisle** [comment]
Thanks for the PR!

You can actually see the structure of the track with `configlet tree`, so the text file is unnecessary and shouldn't be committed in the end.

Can you also modify config.json instead of creating config.1.json.

**Comment by neenjaw** [comment]
Yes, will do

**Comment by neenjaw** [comment]
Changes made -- not sure how the extra config appeared, but it's removed.

**Comment by Cohen-Carlisle** [comment]
```
$ ./bin/configlet tree ./
Elixir
======

core
----
├─ hello-world
│  ├─ nucleotide-count
│  ├─ secret-handshake
│  ├─ rotational-cipher
│  ├─ strain
│  ├─ protein-translation
│  ├─ pig-latin
│  ├─ space-age
│  └─ two-fer
│
├─ rna-transcription
│  ├─ accumulate
│  ├─ acronym
│  ├─ series
│  ├─ raindrops
│  └─ run-length-encoding
│
├─ word-count
│  ├─ twelve-days
│  ├─ scrabble-score
│  ├─ sum-of-multiples
│  ├─ pangram
│  ├─ isogram
│  └─ grade-school
│
├─ roman-numerals
│  ├─ sublist
│  ├─ bracket-push
│  ├─ triangle
│  ├─ flatten-array
│  └─ collatz-conjecture
│
├─ bob
│  ├─ anagram
│  ├─ matrix
│  ├─ phone-number
│  ├─ hamming
│  └─ say
│
├─ beer-song
│  ├─ nth-prime
│  ├─ tournament
│  ├─ leap
│  ├─ binary-search
│  └─ isbn-verifier
│
├─ robot-simulator
│  ├─ all-your-base
│  ├─ meetup
│  ├─ grains
│  └─ binary-search-tree
│
├─ list-ops
│  ├─ simple-linked-list
│  ├─ etl
│  ├─ change
│  ├─ binary
│  ├─ ocr-numbers
│  └─ transpose
│
├─ markdown
│  ├─ kindergarten-garden
│  ├─ scale-generator
│  ├─ luhn
│  ├─ diamond
│  └─ rail-fence-cipher
│
├─ bank-account
│  ├─ parallel-letter-frequency
│  ├─ gigasecond
│  ├─ hexadecimal
│  ├─ prime-factors
│  ├─ perfect-numbers
│  ├─ diffie-hellman
│  └─ palindrome-products
│
├─ zipper
│  ├─ queen-attack
│  ├─ pascals-triangle
│  ├─ saddle-points
│  ├─ minesweeper
│  ├─ connect
│  ├─ custom-set
│  └─ spiral-matrix
│
├─ bowling
│  ├─ sieve
│  ├─ simple-cipher
│  ├─ largest-series-product
│  ├─ crypto-square
│  ├─ allergies
│  ├─ poker
│  ├─ clock
│  └─ armstrong-numbers
│
├─ forth
│  ├─ wordy
│  ├─ atbash-cipher
│  ├─ pythagorean-triplet
│  ├─ difference-of-squares
│  ├─ dot-dsl
│  ├─ grep
│  ├─ dominoes
│  └─ alphametics
-> Cannot find any bonus exercises, this track may be missing a nextercism compatible configuration.
```

**Comment by neenjaw** [comment]
@Cohen-Carlisle what does that error/warning mean?

**Comment by Cohen-Carlisle** [comment]
I was just digging into that. It appears that a "bonus" exercise is one that is not core and is not unlocked by any exercise. This makes it unlock at the beginning of the track, before any core exercise is completed. So before, we actually had all bonus exercises! I think having 2 or 3 bonus exercises for when people first join the track would be ok.

**Comment by Cohen-Carlisle** [comment]
On second thought, I'm kind of confused by the existence of bonus exercises. Should we give varying difficulties, so that people can jump into hard stuff (or easy stuff) straight away without having to progress through the core exercises? Or should it be easy fillers? But why do stuff before hello-world? I'm fine if you want to include bonus exercises or leave this as-is with no bonus exercises.

**Comment by Cohen-Carlisle** [comment]
To add further weirdness to bonus exercises, they appear to unlock after hello-world to the user. Here is a screenshot of the current elixir track, which only contains core and bonus exercises. It shows hello-world unlocking exercises, but just a subset of all the bonus exercises. :thinking:
Screenshot from 2019-04-30 22-31-28

**Comment by neenjaw** [comment]
Ya, I think the bonus exercises unlocked with the completion of the hello world exercise. So if we just nulled out the "hello-world" dependency for the first group it would satisfy that warning and still give a pool of exercises to do.

**Comment by Cohen-Carlisle** [comment]
After some conversations, it seems that bonus exercises are a bit of a deprecated thing now. Having exercises unlocked by hello-world is better. I'll give a day for anyone else to chime in before merging this.

**Comment by Cohen-Carlisle** [comment]
That was a bit more than a day, but its merged now :wink:

**Comment by neenjaw** [comment]
Woo! Thanks for your insights @Cohen-Carlisle.

**Pull request merged**
