### PR TITLE
Correct link https://samuelmullen.com/articles/elixir-processes-send-and-receive

### PR DESCRIPTION
**Pull request by oupfiz5**
With ending "/" page is 404

### CODE REVIEW

**Comment by angelikatyborska** [comment]
Good catch! There are 3 other links in this repository that link to the same website and all have the same problem. Would you be so kind to find them and fix them too?

**Comment by oupfiz5** [comment]
@angelikatyborska I've found only 2 links.

**Comment by oupfiz5** [comment]
@angelikatyborska Done.

**Comment by angelikatyborska** [comment]
The 4th one is in the file `concepts/links/links.json` - it's the same website but a different article. I would have updated it myself but for some reason the Github CLI tool is not letting me checkout your PR 😞 

```
$ gh pr checkout 1266
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), 7.37 KiB | 838.00 KiB/s, done.
From github.com:exercism/elixir
 ! [rejected]          refs/pull/1266/head -> patch-1  (non-fast-forward)
exit status 1

```

**Review by angelikatyborska — APPROVED** [review]

**Comment by angelikatyborska** [comment]
Thank you very much 💜

**Pull request merged**
