### PR TITLE
Fix `Map.fetch` return value

### PR DESCRIPTION
**Pull request by cshintov**
`2` => `{:ok, 2}`

### CODE REVIEW

**Comment by dabaer** [comment]
Thank you for the PR!

You can't update the `/exercises/concept/*/.docs/introduction.md` file directly as it is autogenerated from the files in `/concepts/`.

You'll need to run `./bin/fetch-configlet` and `./bin/configlet --generate` and commit the results.

**Comment by cshintov** [comment]
That's what I did!

I first edited `concepts/structs/introduction.md` and then did this:

> You'll need to run ./bin/fetch-configlet and ./bin/configlet --generate and commit the results.

**Review by angelikatyborska — COMMENTED** [review]
Thank you 🙂 the same error appears in the file `concepts/structs/about.md`, could you fix it there too?

**Comment by cshintov** [comment]
Done. 

I re-ran the `configlet generate` again. But it didn't have any effect this time.

**Comment by angelikatyborska** [comment]
That's correct, only introduction files are affected by the autogeneration. Thank you!

**Review by angelikatyborska — APPROVED** [review]

**Pull request merged**
