### PR TITLE
Reorder concept exercises to follow concept tree order

### PR DESCRIPTION
**Pull request by angelikatyborska**
The order of concept exercises in the config is important as it's used on the website a lot.

I think it makes most sense to order them roughly in the same order as you would see their concepts in the concept tree. That should correspond to "easiest to most difficult" of practice exercises.

I did the reordering manually by looking at the concept tree. Github won't be very useful in displaying the diff...

Here's the new order

```
[
  'lasagna',
  'secrets',
  'pacman-rules',
  'freelancer-rates',
  'log-level',
  'language-list',
  'guessing-game',
  'kitchen-calculator',
  'high-school-sweetheart',
  'bird-count',
  'high-score',
  'city-office',
  'german-sysadmin',
  'date-parser',
  'rpg-character-sheet',
  'name-badge',
  'take-a-number',
  'wine-cellar',
  'dna-encoding',
  'library-fees',
  'basketball-website',
  'boutique-inventory',
  'file-sniffer',
  'newsletter',
  'chessboard',
  'remote-control-car',
  'boutique-suggestions',
  'community-garden',
  'bread-and-potions',
  'captains-log',
  'need-for-speed',
  'rpn-calculator',
  'stack-underflow',
  'rpn-calculator-output',
  'rpn-calculator-inspection',
  'lucas-numbers',
  'mensch-aergere-dich-nicht'
]
```

old order:
```
[
  'lasagna',
  'pacman-rules',
  'freelancer-rates',
  'log-level',
  'language-list',
  'guessing-game',
  'secrets',
  'kitchen-calculator',
  'high-school-sweetheart',
  'name-badge',
  'high-score',
  'bird-count',
  'german-sysadmin',
  'basketball-website',
  'file-sniffer',
  'dna-encoding',
  'boutique-inventory',
  'rpn-calculator',
  'remote-control-car',
  'stack-underflow',
  'wine-cellar',
  'rpn-calculator-output',
  'take-a-number',
  'mensch-aergere-dich-nicht',
  'community-garden',
  'date-parser',
  'boutique-suggestions',
  'bread-and-potions',
  'rpg-character-sheet',
  'captains-log',
  'chessboard',
  'newsletter',
  'library-fees',
  'rpn-calculator-inspection',
  'lucas-numbers',
  'city-office',
  'need-for-speed'
]
```

### CODE REVIEW

**Comment by jiegillet** [comment]
I'm glad `secrets` is a bit lower, I picked it and solved because it was on top to try the new interface and I was surprised that the second thing after hello world was currying/partial application.

**Review by neenjaw — APPROVED** [review]
looks good to me

**Comment by angelikatyborska** [comment]
@jiegillet I put it after booleans and integers now because they're all "at the same level" 😅. But do you think the exercise is actually too difficult? Because IMO it just teaches how anonymous functions are actually used in normal Elixir code. You don't need to know if it has a fancy name or not to use it 😅.

**Comment by jiegillet** [comment]
It is how anonymous functions are used in Elixir, but few "mainstream" languages use anonymous functions quite as much, and it's a very abstract concept to learn. 

I teach programming regularly, and I'm often reminded that things that feel super intuitive to me can be hard to learn (even without the fancy names), so maybe I now I take a too conservative approach :)

I think it's fine though, I jumped straight into the exercise without reading the instructions and assume it was only about bitwise operations so I was a bit surprised. The instructions are clear enough.  Let's see the student feedback before panicking :)

**Comment by angelikatyborska** [comment]
> I teach programming regularly

That makes you 10x more valuable as a maintainer here 😍 I would love to know what you think about the other concept exercises. They weren't very well tested so far.

**Comment by jiegillet** [comment]
Yes, I will have a look at some point ^^

Quick question on something I noticed, now the exercises show the example solution. I assume this will not be in the final website right?

**Comment by angelikatyborska** [comment]
Yes, this is so that you can copy-paste working solutions to move through the track quickly to test things. It will be removed.

**Comment by jiegillet** [comment]
Makes sense. Except that I can't seem to be able to select any text on the right banner. I'm using Safari.

**Comment by angelikatyborska** [comment]
Indeed there's something weird about text selection, I opened a bug report: https://github.com/exercism/v3-beta/issues/115

**Pull request merged**
