### PR TITLE
New concept exercise `city-office` (`docs` and `typespecs`)

### PR DESCRIPTION
**Pull request by angelikatyborska**
WIP!

### CODE REVIEW

**Review by neenjaw — COMMENTED** [review]
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 So good, great investigation to discover this method for testing. Love the exercise, I think it will be awesome.

Where were you thinking about having it in the track? early after we introduce major value types? Then we could go back an add in `@spec`s to other exercises.

**Comment by angelikatyborska** [comment]
> Where were you thinking about having it in the track? early after we introduce major value types? 

The decision to include a struct in this exercise unfortunately forces rather late in the tree, after structs. That's not great, I might want to remove the `Address` struct and replace it with something else that deserves its own custom type, maybe map? Maps are much earlier in the concept tree.

> Then we could go back an add in @specs to other exercises.

I don't have a strong opinion for or against this, but if some exercises got specs, then they would have to require the typespecs concept. If we don't do that, then the concept remains entirely optional 🤔

**Comment by neenjaw** [comment]
If you rebase on main, it will then drop the 1.6 ci check. 😄

**Comment by angelikatyborska** [comment]
I'll sneak in some more reputation points in this PR 🐍 I think every PR that adds a whole exercise should a major one.

**Review by neenjaw — APPROVED** [review]

**Comment by neenjaw** [comment]
Looks great!

**Pull request merged**
