### PR TITLE
Student-facing docs refresh

### PR DESCRIPTION
**Pull request by angelikatyborska**
At first I only wanted to fix links for v3, e.g.:
- `https://exercism.io/tracks/elixir/resources` -> `https://exercism.io/docs/tracks/elixir/resources`
- `https://exercism.io/my/tracks/elixir` -> `https://exercism.io/tracks/elixir`

But then I read the docs and also decided to:
- Rephrase "learning" because it suggested that Exercism is not good for LEARNING Elixir, which is no longer true with the syllabus.
- Reformat resources because it was a bit silly to have each link in a one-element list with its own heading. I also added a list of podcasts and newsletters.
- I fixed the outdated IRC link and added a Discord link.

Closes https://github.com/exercism/elixir/issues/850

### CODE REVIEW

**Comment by angelikatyborska** [comment]
@jiegillet could you take a look at this PR is it looks ok to you?

**Comment by jiegillet** [comment]
It does, I checked all the URLs you modified (minus the IRC one, and the exercism links with the `/docs/` that don't work yet, I think). I did not check all other 500 links that are everywhere on the repo :p

**Comment by jiegillet** [comment]
I checked the open issue again:
- the current links in `HELLO.md` work for me, also in private browsing. Not sure why they were flagged
- the links in the `reference` folder don't matter, do they?

**Comment by angelikatyborska** [comment]
> the current links in HELLO.md work for me, also in private browsing. Not sure why they were flagged

I pinged Erik so that he checks his link checker script

> the links in the reference folder don't matter, do they?

right, they don't, I think they were written for v3 work preparation and it's all internal stufff

**Comment by angelikatyborska** [comment]
@exercism/maintainers-admin Please approve, it was already reviewed by @jiegillet

**Review by iHiD — APPROVED** [review]

**Pull request merged**
