### PR TITLE
"Mixify" hello-world and nucleotide-count

### PR DESCRIPTION
**Pull request by amencarini**
As discussed in https://github.com/exercism/elixir/issues/414, this shows how exercises refactored to use `mix` would look like.

This can be further simplified if necessary. `.formatter.exs`, `.gitignore`, and the `config` directory can be removed and everything would still work.

### CODE REVIEW

**Comment by NobbZ** [comment]
You need to update the testrunner as well, also I'm not a fan of porting the exercises piece wise, it should happen all at once or not at all.

**Comment by amencarini** [comment]
@NobbZ agreed that we should either port everything or nothing, this is to provide a sample as @devonestes asked in the issue.

re: the test runner, it needs no change, the problem with the build you saw was due to `hello_world_test.exs` having a `doctest` call that wouldn't work with the way tests are run across the exercises. That has been fixed.

**Comment by devonestes** [comment]
Thanks for the PR!

I think if we're going for full compatibility with a standard mix project, we'll need to keep all the files that are normally generated when you do `mix new`. It's a lot of files, and many of them are unneeded, but that's part of the cost of going that route - bloat. Personally, after seeing the changes, I'm a little less enthusiastic about it.

The reason for that is that most of these exercises aren't really applications, but more like single functions. It would make sense to me if we could somehow get all of the exercises into a single mix application, but individual mix apps for each exercise feels a little weird to me. Am I the only one who's thinking that?

**Comment by amencarini** [comment]
I think that despite the bloat, the "this is what real world apps look like" approach is worth the cost, and am still leaning towards 1 mix project per exercise. I know I might be biased because I am very familiar with that structure.

It would be interesting to take a couple of possible students, an experienced programmer that doesn't know Elixir and someone very new to programming, and ask them to complete a couple of exercises with the mix project structure (and amended documentation). Depending on the level of the struggle they encounter we could make a more informed decision on this.

**Comment by neenjaw** [comment]
Out of curiosity, what is the status of this? Is the issue man-power and mixifying the course? or have the winds of opinion changed on this?

As @NobbZ mentioned in #478, `Code.load_file` has been soft deprecated and should be evaluated for migration to the newer implentations, so this could be an opportunity for that.

**Comment by Cohen-Carlisle** [comment]
I think the issue is just getting the time to do this. I'm still in favor of it as it shows elixir as you'll encounter it in real-world projects.

**Comment by neenjaw** [comment]
Ok, I have boiled it down to about 10 steps, working on a shell script that will just do it all programmatically and can probably submit a pull request with all of the exercise updates in a day or two.

**Comment by neenjaw** [comment]
I think it's almost ready for a pull request, will submit tomorrow or the next day.  If you want to see a preview, check out my forked branch here: https://github.com/neenjaw/elixir/tree/mixify-exercises

**Comment by neenjaw** [comment]
This PR has now been accomplished with PR #480.  Close this issue?

**Pull request closed without merging**
