### PR TITLE
Updated meetup instructions

### PR DESCRIPTION
**Pull request by tradfursten**

### CODE REVIEW

**Comment by tradfursten** [comment]
It is possible to add the hacktoberfest-accepted label?

**Comment by jiegillet** [comment]
> It is possible to add the hacktoberfest-accepted label?

Hi @tradfursten! 
Sure, we can add that label, but I feel that it is worthy of a tiny bit more effort 😇 
I see from running `bin/configlet sync` that we are missing a test case for `matching-brackets`, would you consider doing that too in this PR? The instructions are [here](https://github.com/exercism/elixir/issues/1027).

**Comment by tradfursten** [comment]
I'll fix the tests :)
I thought I was suppose to have one pr per thing I fixed :)

**Review by jiegillet — APPROVED** [review]
> I thought I was suppose to have one pr per thing I fixed :)

Well, generally yes, but I do have the bandwidth to handle a +9/-1 PR :)

Thank you!

**Comment by jiegillet** [comment]
@tradfursten there was just a big batch of problem-specs update, if you want another label :)

**Comment by tradfursten** [comment]
> @tradfursten there was just a big batch of problem-specs updates, if you want another label :)

Nice :)

**Pull request merged**
