### PR TITLE
track improvement round 1

### PR DESCRIPTION
**Pull request by Cohen-Carlisle**
This PR is the result of work being done to structure the exercises in a track according to the [Track Anatomy Project](https://exercism.io/blog/track-anatomy-project). 

This is work in progress. This first step (of several rounds) attempts to fix obvious problems with the sequence of the existing core exercises, and removes Math and DIY (reimplementing standard methods) exercises from the core track. The result is as follows:

1. hello-world
1. rna-transcription
1. word-count
1. roman-numerals
1. bob
1. beer-song
1. robot-simulator
1. list-ops
1. markdown
1. bank-account
1. zipper
1. bowling
1. forth

The most notable changes are:

- binary-search: now side because of the policy to exclude math-y / std lib-y exercises from core track
- clock: now side as it re-implements std lib
- robot-simulator: now occurs just prior to list-opts and markdown, but has a higher pre-existing difficulty score than either.

Upcoming Rounds will zoom in on evaluations of each exercise. In this Round the focus is on a quick fix of the reordering and removals only.
We're aiming for small and fast PR's that cause (huge) improvements for the majority of the students and mentors.

The current ordering is not final, and there is still lots to improve, but I feel it is definitely an improvement over the current situation. I'm interested in hearing your thoughts!

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Great! @Cohen-Carlisle , if you run `configlet tree` you get a nice tree view of the new structure.

**Comment by chriseyre2000** [comment]
Zipper is tougher than list ops.

**Comment by Cohen-Carlisle** [comment]
Updated tree view: (note that in practice all side exercises are unlocked by hello-world)
```
$ bin/configlet tree .
Elixir
======
-> Cannot find any unlockable exercises, this track may be missing a nextercism compatible configuration.

core
----
├─ hello-world
│
├─ rna-transcription
│
├─ word-count
│
├─ roman-numerals
│
├─ bob
│
├─ beer-song
│
├─ robot-simulator
│
├─ markdown
│
├─ bank-account
│
├─ list-ops
│
├─ zipper
│
├─ bowling
│
└─ forth

bonus
-----
nucleotide-count
secret-handshake
rotational-cipher
strain
protein-translation
pig-latin
space-age
twelve-days
accumulate
acronym
series
raindrops
run-length-encoding
sublist
scrabble-score
sum-of-multiples
pangram
simple-linked-list
anagram
matrix
bracket-push
phone-number
nth-prime
all-your-base
hamming
triangle
isogram
grade-school
tournament
flatten-array
leap
kindergarten-garden
etl
meetup
grains
change
parallel-letter-frequency
binary
scale-generator
luhn
gigasecond
queen-attack
pascals-triangle
saddle-points
hexadecimal
diamond
binary-search
binary-search-tree
prime-factors
perfect-numbers
diffie-hellman
sieve
wordy
atbash-cipher
simple-cipher
largest-series-product
crypto-square
pythagorean-triplet
allergies
palindrome-products
rail-fence-cipher
minesweeper
connect
difference-of-squares
poker
dot-dsl
custom-set
clock
grep
say
ocr-numbers
collatz-conjecture
dominoes
transpose
isbn-verifier
spiral-matrix
alphametics
two-fer
armstrong-numbers
```

**Comment by SleeplessByte** [comment]
Is there a reason that exercises are not unlocked by other core-exercises? Might be a nice time to get that in as well?

**Comment by Cohen-Carlisle** [comment]
I'm assuming the work was just never done to map side exercises to core exercises. It's definitely something we should do, but I don't think it should be done with this work as it's a pretty big undertaking on its own.

**Comment by SleeplessByte** [comment]
I think that's a good reason to delay. Perhaps it could be a community effort after this merges? It might all change with round 2 and beyond tho, so don't spend _too_ much time 👍

**Comment by devonestes** [comment]
My thoughts:

1) `robot simulator` and `bank account` are both OTP exercises, and so they're conceptually more difficult than `list ops`. At that point in the track `list ops` teaches nothing new, so then should it even be part of the core track?

2) `bowling` has a very large problem space to cover with many edge cases, but the solutions to those problems are conceptually simple. If it is this late in the track I'm not sure learners will learn anything new, so should it still be part of the core track?

3) `roman numerals` and `beer song` are conceptually very similar - essentially they're about handling edge cases when translating strings to integers. Do they both belong in the core track? Also, `roman numerals` is more difficult conceptually than `beer song`, so should their positions be switched?

**Comment by Cohen-Carlisle** [comment]
1. I don't think I agree that robot-simulator and bank-account are harder than list-ops, or that list-ops teaches nothing new. When I did list-ops it kind of melted my brain because it forced me to really, really grasp functional programming in a way I had not been made to up until that point. On the other hand, robot-simulator doesn't require OTP at all, while bank-account can be be solved with Agents, which are very simple to use.

2. I kind of agree with you on bowling, but I'm not sure now is the time to dig deeply into each exercise.

3. I actually view beer-song and roman-numerals as different. Yes, they both work on strings, but roman-numerals is very straight forward once the algorithm is known while beer-song is fuzzy in the same way bob is: the requirements are fuzzy which I think makes it harder.

This makes me think we should return to these more in-depth questions at a later stage. Maybe Maud can chime in with the best time tackle these deeper questions?

**Comment by SleeplessByte** [comment]
> Edit: For some context, the only exercises that were recommended for removal from core were exercises that were math heavy or involve re-implementing the standard library

And I think you should stick to it 👍 In later rounds you will explicitely start promoting new exercises or removing old ones 💯 .

Question: what is `OTP` in this context? One-time password or padding doesn't seem right?

**Comment by devonestes** [comment]
@Cohen-Carlisle Is the intention to do this update in several steps, or to do one large change of the track? If it's done in several steps, how will that affect people currently somewhere in the middle of the track?

Since `markdown` is about refactoring something that would ideally utilize recursion and pattern matching somewhat heavily, should `list ops` come before it so folks have a better grasp of those concepts before attempting that refactor?

Also, if one of the goals is to remove exercises that re-implement the standard library from core, would it make sense to remove `list ops`?

**Comment by SleeplessByte** [comment]
@devonestes this PR would be merged in its entirety. Someone in the middle of the track will simply have marked off those exercises they did before, but will need to do the first core exercise they have not yet completed.

**Comment by Cohen-Carlisle** [comment]
@SleeplessByte:
> what is OTP in this context?

[Open Telecom Platform](https://en.wikipedia.org/wiki/Open_Telecom_Platform), which is a misnomer at this point. OTP is a set of libraries that come with erlang/elixir and provide robust concurrency, fault-tolerance, and distributed programming tools and the ability to hold state.

---

@devonestes 
> Is the intention to do this update in several steps?

Yes, very much so.

> how will that affect people currently somewhere in the middle of the track?

As @SleeplessByte said, it would just mean they would pick up the next core exercise according to the new order.

> should list ops come before [markdown] [...] ?

Good idea. List-ops is a hard one for me to classify because it basically broke and remade by brain to truly think functionally when I was beginning to learn elixir. I'll push a change soon.

> would it make sense to remove list ops?

It could. I kept it because I actually brought up removing it before but it was nearly unanimous against me that list ops should be kept as it really teaches functional thinking and recursion.

**Comment by F3PiX** [comment]
> This makes me think we should return to these more in-depth questions at a later stage. Maybe Maud can chime in with the best time tackle these deeper questions?

>Is the intention to do this update in several steps, or to do one large change of the track? 

We're currently working on documenting the separate steps of the Track Anatomy Project. Sorry to keep in you in the dark. We're currently testing the Tool, and things are changing a lot, which makes documenting a...... challenge. 
As @Cohen-Carlisle stated in the OP, this PR is covering a first step, that is meant as a quick fix for most obvious problems. It is in no way meant to be the final answer to the question what the optimal order of exercises is. 
What it _should_ do is remove some conspicuous problems for students and mentors. That's a different goal than creating the optimal experience. That's a bigger task, and that's what the upcoming changes are for.  

We asked @Cohen-Carlisle to make pragmatic choices; that means that it's very likely that math and DIY exercises are banned at the beginning of the track, but tolerated later on. For now. And up for evaluation later.   

In the upcoming weeks, there will be multiple smaller PR's that focus on different parts of the track. 

Evaluation of the separate exercises is not within scope of this PR. In later Rounds of the project the core exercises will be analyzed one by one and in relation to each other. 

It is important that the side exercises will be unlocked by core exercises, but again, that's also a big task, and the focus is on the core exercises. It would be awesome if someone else would take on the task of at least dividing the side exercises over the core exercises. I'd recommend to create an issue for that. And keep it simple: at this point, it's way more important that the side exercises are equally divided, than it is to have them on a perfect position. Because, this too will change in the coming weeks. 

I'd recommend to continue the discussing _about_ the changes or this explanation in a separate issue, as not to block merging this PR.

**Comment by devonestes** [comment]
@F3PiX @Cohen-Carlisle My only concern about the incremental approach would be about the user experience of folks currently in the track. If merging several changes to the track in several PRs will result in several changes to their experience while they're progressing through the track, I could see that as an unsettling user experience for them if things are changing so frequently under their feet, and that could reduce their likelihood of finishing the track.

If that's not something that y'all are worried about - or even see that as an advantage over making one large change, which I could see as a possibility - then I have no problem merging this and then making further changes incrementally.

@Cohen-Carlisle I personally think `list ops` is probably the most important and fundamental exercise in the whole track, so I'm strongly in favor of keeping it. However, that's based on nothing by my limited experience in teaching Elixir to a few devs as part of my consulting work, and in speaking with folks that I've met at conferences, online, etc. about what their struggles were in learning Elixir (and FP as a broader topic).

If y'all have actual _data_ about how that exercise, or that placement of that exercise, is hindering learners from continuing on with their progression in the track, I would gladly remove it. The thing I think is most important is that folks get through the core track and get that feeling of accomplishment. That will keep them engaged with further learning of the language far more than simply completing an exercise that will be really helpful for them later on.

If I recall correctly, this Track Anatomy Project is based on such data, so I'll happily accept the recommendations that come out of that project since, in reality, I have no idea what I'm doing here :wink:. I'm just going off of anecdotal evidence and personal preference: two things that are notoriously unreliable as factors in decision making. I suggested removing `list ops` since one of those recommendations was to remove exercises that re-implement features in the standard library, and that's exactly what `list ops` is.

**Comment by Hanspagh** [comment]
@Cohen-Carlisle @devonestes
I don't see the purpose of `list ops` to be reimplementation features in standard lib, but rather a very effective method of teaching recursion. If done correctly, you can solve the whole exercise using own implementation of reduce and reduce (pun intended) the amount of self written recursive functions, which is something I see a lot of people are struggling with.

**Comment by Cohen-Carlisle** [comment]
As I alluded to earlier, list-ops is very hard for me to judge because it was very hard for me to complete at the time I did it but now seems easier in hindsight (and with the lessons it taught me about recursion and functional thinking). I'm ok keeping it in the track for now and then digging down into what it's teaching and how it impacts students later.

**Comment by Cohen-Carlisle** [comment]
I'm planning to merge this in about 48 hours, unless there are major requests for changes. :shipit:

**Pull request merged**
