### PR TITLE
Make angelikatyborska visible on the website as a maintainer

### PR DESCRIPTION
**Pull request by angelikatyborska**
A follow up to https://github.com/exercism/elixir/pull/536#issuecomment-630486639

I would like some of that fame now, please 😺

### CODE REVIEW

**Review by neenjaw — APPROVED** [review]

**Comment by neenjaw** [comment]
:tada: :parrot:

**Comment by neenjaw** [comment]
@iHiD

**Comment by iHiD** [comment]
FAME.

**Comment by iHiD** [comment]
I promise you both all the fame once we launch v3 :)

**Pull request merged**
