### PR TITLE
Fix, elem/1 -> elem/2

### PR DESCRIPTION
**Pull request by anrgl**

### CODE REVIEW

**Review by jiegillet — APPROVED** [review]
Thank you very much, that's better :)

**Comment by angelikatyborska** [comment]
@anrgl thank you! All of the concept introductions (`concepts/**/introduction.md`) are copy-pasted into concept exercise introductions (`exercises/concept/**/./docs/introduction.md`). Could you also do the same fix in the file `exercises/concept/kitchen-calculator/.docs/introduction.md`?

This duplication will be fixed in https://github.com/exercism/elixir/issues/686 but it's blocked until https://github.com/exercism/configlet starts supporting templates.

**Comment by anrgl** [comment]
Hi @angelikatyborska, @jiegillet thank you! I have one question. Is it right way creating new PR or need merge in this PR?

**Comment by angelikatyborska** [comment]
@anrgl For the future, the best way would be adding a new commit to this PR. That's why we were waiting before merging this PR. But there's no need to fix that now, I'll just merge both PRs now 🙂 Thanks again!

**Pull request merged**
