### PR TITLE
[German Sysadmin] Make sentence slightly friendlier

### PR DESCRIPTION
**Pull request by iHiD**
This is me testing the new GHA comments flow 🎉 

I don't expect this PR to be merged (unless you like the change, in which case more rep for me++)

### CODE REVIEW

**Comment by angelikatyborska** [comment]
Interesting that this didn't work 🤔 I did a test earlier that did work (https://github.com/exercism/elixir/pull/713).

The output has no errors, just says:
> matched snippet ids: 

Which would suggest the action is fine, but configuration file is not doing what I wanted it to do.

**Comment by angelikatyborska** [comment]
You could set `ACTIONS_STEP_DEBUG` as a secret in this repo and rerun the action, this would give us more logs.

**Comment by neenjaw** [comment]
I think you have to pass the dot option to `Minimatch.match`: [docs](https://www.npmjs.com/package/minimatch#dot)

**Comment by angelikatyborska** [comment]
I created an issue so that we don't forget: https://github.com/exercism/pr-commenter-action/issues/1 

I'll try to work on this soon.

**Review by angelikatyborska — APPROVED** [review]

**Comment by iHiD** [comment]
Wahoo. I did Elixir! 🎉

**Pull request merged**
