### PR TITLE
Add more tests to `say`

### PR DESCRIPTION
**Pull request by aifrak**
I had few cases where all tests passed but some numbers I tried were not correct.

It was a while ago, so I do not remember clearly, but it was between 20 and 1000.

### CODE REVIEW

**Comment by jiegillet** [comment]
Thank you for the contribution.
The usual way to add tests is through the [problem-specifications](https://github.com/exercism/problem-specifications) repo, where exercises and tests are defined for all tracks. Maybe you can try opening a PR over there?

**Comment by aifrak** [comment]
I have created a [PR](https://github.com/exercism/problem-specifications/pull/2087) in the [problem-specifications](https://github.com/exercism/problem-specifications) repository with the 4 new tests.

**Comment by aifrak** [comment]
[PR](https://github.com/exercism/problem-specifications/pull/2087) related to this ticket in the [problem-specifications](https://github.com/exercism/problem-specifications) has been accepted.

**Comment by neenjaw** [comment]
Your PR in problem specifications has been merged, you will need to also:
- update the `tests.toml` config
- add yourself as a contributor to this practice exercise in the `.meta/config.json`.

**Comment by aifrak** [comment]
`tests.toml` and `.meta/config.json` have been updated.

**Review by neenjaw — APPROVED** [review]
Looks good, I have approved and added the hactoberfest label. We don't advertise, but in the case you're participating, we recognize the valuable contribution here. 

Thanks for sticking it through!

**Pull request merged**
