### PR TITLE
fix doc the IsbnVerifier

### PR DESCRIPTION
**Pull request by herminiotorres**

### CODE REVIEW

**Comment by neenjaw** [comment]
Just looking at this, I wonder if this module should be changed to ISBNVerifier rather than changing the docs.

**Comment by Cohen-Carlisle** [comment]
I think this is the correct change. Initialisms and acronyms usually just get their first letter capitalized in the rest lower case. This is nice since a programmatic case changer can't tell the difference between them and real words.

**Comment by herminiotorres** [comment]
good point @Cohen-Carlisle

**Comment by neenjaw** [comment]
Sounds good, I think it was the other way before we set up each exercise as a mix project. 

I don't know why TravisCI failed with the configlet. Is there a way to re-trigger it?

**Comment by Cohen-Carlisle** [comment]
Hmm, I'm not sure, to be honest. if it can't be rerun I think it's fine to merge this as is since it's documentation only and wouldn't have caused the build to fail.

**Comment by herminiotorres** [comment]
I could try to close and reopen the pull-request and hope the CI trigger again

**Comment by Cohen-Carlisle** [comment]
I'll just merge! :wink:

**Pull request merged**
