### PR TITLE
change dot-dsl pratices to ast

### PR DESCRIPTION
**Pull request by dongdigua**
I think it should be ast :)

### CODE REVIEW

**Comment by angelikatyborska** [comment]
I agree that `ast` could be added as `practices` to `dot-dsl` but I'm not sure about removing `keyword-lists`. There is no other exercise in the track that practices `keyword-lists`, a situation that should be avoided. @jiegillet You have solved this exercise before, would you agree that it's damaging to recommend it to practice `keyword-lists`? I looked at community solutions but it's still not clear to me.

**Comment by jiegillet** [comment]
I also agree on adding `ast`, and keyword list are important too (to a lesser extent) so we could leave both, that's no problem.
I am a bit concerned that this is the only exercise to practice keyword lists though, because it is very advanced. Maybe we should find a couple more exercises more suited for it (not in this PR necessarily).

**Comment by dongdigua** [comment]
ok, I added keyword-lists to dot-dsl.

**Review by angelikatyborska — APPROVED** [review]
Thank you 🎉

**Pull request merged**
