### PR TITLE
End two-fer test sentences with dot

### PR DESCRIPTION
**Pull request by mpas97**
Be consistent with the instructions.

grafik

### CODE REVIEW

**Comment by jiegillet** [comment]
Looks good to me, this is actually aligned with the [problem-specification tests](https://github.com/exercism/problem-specifications/blob/main/exercises/two-fer/canonical-data.json), however, could you also update the example implementation in `.meta/example.ex` so that the test will pass with it?

**Comment by mpas97** [comment]
@jiegillet Sure, already done!

**Review by jiegillet — APPROVED** [review]
LGTM, thank you.
I'll let @angelikatyborska have another look and merge, because somehow `two-fer` feels like a legendary and sacred exercise to me 😆

**Comment by angelikatyborska** [comment]
Haha, it is a "legendary" exercise because it's the easiest one, it has been used as the first test case for writing analyzers by a lot of tracks. 

I took a look at the analyzer and it seems like it will still work the same after adding the dot, but we need to bring it up to date with this change too. Dots would need to be added everywhere in the strings in this file: https://github.com/exercism/elixir-analyzer/blob/main/test/elixir_analyzer/test_suite/two_fer_test.exs and in those 4 copies of the exercise https://github.com/exercism/elixir-analyzer/tree/main/test_data/two_fer (note the 3 of them are wrong on purpose because they're test fixtures for the analyzer).

Otherwise I'm fine with this change. The problem specifications say there needs to be a dot.

**Comment by jiegillet** [comment]
And that is exactly why we should import those via a git submodule... 
@mpas97 would you fell up to making the same change in the `elixir-analyzer` repo? The price of meddling with a legendary exercise :p

**Comment by mpas97** [comment]
@jiegillet Nice price 😁 @angelikatyborska Hopefully I got all files exercism/elixir-analyzer#141 ;)

**Pull request merged**
