### PR TITLE
change to poker tests in ref to issue #554

### PR DESCRIPTION
**Pull request by MeerKatDev**
@neenjaw could you have a look?

### CODE REVIEW

**Comment by neenjaw** [comment]
I'll take a look after work today. 👀

**Comment by neenjaw** [comment]
❤️ Thanks for opening this PR, what if we did something simpler so that we can leverage ExUnit's diff on failure?

```elixir
  defp assert_poker(dealt_hands, expected_winning_hands) do
    winnings_hands = dealt_hands |> Poker.best_hand() |> Enum.map(&Enum.sort/1) |> Enum.sort()
    expected_winning_hands = expected_winning_hands |> Enum.map(&Enum.sort/1) |> Enum.sort()

    assert winnings_hands == expected_winning_hands
  end

  # @tag :pending
  test "single hand always wins" do
    high_of_jack = ~w(4S 5S 7H 8D JC)
    assert_poker([high_of_jack], [high_of_jack])
  end
```

Then if this fails it gives us:

```
 1) test single hand always wins (PokerTest)
     test/poker_test.exs:12
     Assertion with == failed
     code:  assert winnings_hands == expected_winning_hands
     left:  [["4S", "5S", "7H", "8D", "JC"]]
     right: [["4S", "5S", "7H", "8D", "KC"]]
     stacktrace:
       test/poker_test.exs:14: (test)
```

Thoughts?

**Comment by MeerKatDev** [comment]
That doesn't sort the the letter-cards (A, J, Q, K) and the diff works anyway in the code I posted (manually, of course).
To use `Enum.sort` you have to implement some more complicated custom sorting for the above reason - I did implement it while doing the exercise and it's much more prone to error than this MapSet.equal strategy.
Moreover, this function I put in the PR is already used in another exercise.. so nothing new under the sun

**Comment by MeerKatDev** [comment]
On a second thought, that might work as well, because whatever order you use, it's used for both lists.
I still prefer the first version because it's more adequate to the case at hand (the order shouldn't matter), but as you prefer.

**Comment by neenjaw** [comment]
Like your original issue said, the order of the cards in your hands isn't specified by the problem spec, so like your second thought here, I am also in agreement that the card order doesn't matter.  What I think is important is the color-coded diff which isn't available in your function (or the function implemented by the `allergies` problem).

Your assertion function also requires the order of the expected hands to be in a specific order for the comparison to work, for ex: If you reverse the expected hands on line 45, the test fails.

https://github.com/exercism/elixir/blob/b5d5597793707e2f0fcb993de33867237f6daf6e/exercises/poker/test/poker_test.exs#L45

So If we are going to implement a function that compares the equality of the returned vs the expected agnostic to the order of the cards in the hand, it should also be able to compare the list of hands agnostic to the order of the list returned.

**Comment by neenjaw** [comment]
I think it's also important to point out that while many of the examples are examples of good code, some aren't perfect and there is room for improvement / iteration in many exercises.  Which underscores is why I think we should advance this exercise's test suite to the next level, like you suggested in the issue, to create a better experience for students.

In the case of this exercise, it keeps the focus on the problem of determining poker hand winners, not on ordering a list which has no external meaning.

**Comment by MeerKatDev** [comment]
Feel free to change this PR with the code you proposed, then :)

**Comment by neenjaw** [comment]
Closed due to merge conflicts, PR recreated with new repo structure at #585

**Pull request closed without merging**
